### ISSUE TITLE
[1.21] Latest mod version crash with NeoForge

### ISSUE THREAD

**Issue by Periam** [baguchan/EnchantWithMob-Forge#12]
Installing the latest version of the mod and latest version of Neoforge the game crash opening or creating worlds.

NeoForge 21.0.139
Bagus_lib-1.21-12.4.1
enchantwithmob-1.21-19.2.1
jei-1.21-neoforge-19.5.2.66

[debug.log](https://github.com/user-attachments/files/16397324/debug.log)
[latest.log](https://github.com/user-attachments/files/16397325/latest.log)
[crash-2024-07-26_19.33.47-client.txt](https://github.com/user-attachments/files/16397326/crash-2024-07-26_19.33.47-client.txt)

 
![Screenshot 2024-07-26 193420](https://github.com/user-attachments/assets/86b8d274-17db-4856-8c5e-83c66678fb85)

**Comment by baguchi** [comment]
fixed in next version!
