### ISSUE TITLE
[Bug]: Neo 1.21.1 Client Crash at Startup - 20.3.0

### ISSUE THREAD

**Issue by Soforak** [baguchan/EnchantWithMob-Forge#18]
Since version 20.3.0 the game crash at startup
It worked fine on 20.2.1

Neoforge 21.1.89
Minecraft 1.21.1
EnchantWithMob 20.3.0

Here's the crash report:
https://gist.github.com/Soforak/43ddf831acc3ce3cc8d06efc5fa0ac76

And what I get on screen:
![image](https://github.com/user-attachments/assets/a9bf00eb-2811-409a-a36e-c87b367e3c0c)

**Comment by baguchi** [comment]
sorry for delay. fixed in 1.21.1-20.3.1!

**Comment by Soforak** [comment]
Ahah nice delay!
Thanks a lot, it now works fine
