### ISSUE TITLE
[1.18.2] Immediate crash when launching game

### ISSUE THREAD

**Issue by XtorWorkgroup** [baguchan/EnchantWithMob-Forge#19]
Hello!
Forge version is 40.0.19.
OptiFine version is HD_U_H6.
The game crashes instantly and does not even allow you get to main menu.
"Failure message: Enchant With Mob (enchantwithmob) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/RegistryEvent$NewRegistry"
		
[crash-2022-03-18_22.37.12-fml.txt](https://github.com/baguchan/EnchantWithMob-Forge/files/8305861/crash-2022-03-18_22.37.12-fml.txt)

**Comment by BugmanBugman** [comment]
Getting this too

**Comment by Insane96** [comment]
Try with older version of forge (iirc 40.0.17)

**Comment by ModernGamingWorld** [comment]
That's cause forge 40.0.18 breaks mods and @baguchan will need to update this mod to fix it to work on the New forge versions, a few mods have already done just that

**Comment by baguchan** [comment]
sorry for late. 1.18.2-4.0.1(fixed version) is released.
you should use that
