### ISSUE TITLE
[CRASH] The Enchanter Crashes the Game

### ISSUE THREAD

**Issue by ZilverLazarus** [baguchan/EnchantWithMob-Forge#2]
The mod works as you'd expect, right until you try to /summon the Enchanter or spawn in it using its spawn egg. I assume this also happens if it were to spawn naturally as the entity itself seems to be crashing the game.

Mod Version: enchantwithmob-1.19.2-11.4.0
MC Version: 1.19.2
Forge Version: 43.3.2

[crash-2023-10-20_11.10.49-client.txt](https://github.com/baguchan/EnchantWithMob-Forge/files/13057057/crash-2023-10-20_11.10.49-client.txt)

**Comment by baguchi** [comment]
seems like illager's wear armor's enchant with mob compat not working and causing it
also Illager wear armor's author said no longer update 1.19.2 in this page. so let me know
https://github.com/seymourimadeit/IllagersWearArmor/issues/27
