### ISSUE TITLE
1.18.2 fails to launch on Forge 40.0.18 and greater. 

### ISSUE THREAD

**Issue by TehFoxFire** [baguchan/EnchantWithMob-Forge#20]
MC Version: 1.18.2
Forge version: 40.0.22
Crash Report: https://gist.github.com/TehFoxFire/eecacd0ac029ed20d433612c2ab1ed85

**Comment by Corvus20** [comment]
I am having this same issue.

**Comment by baguchan** [comment]
sorry for late.
This problem solved when using newer version about 1.18.2-4.0.1
