### ISSUE TITLE
error in the server console.

### ISSUE THREAD

**Issue by Taknax** [baguchan/EnchantWithMob-Forge#21]
I am using mc 1.16.5 and for 36.2.33. The mod version of EWM is 1.5.2.
I got this on my seversconsole

[Server] main/WARN [ne.mi.co.ForgeHooks/]: Called deprecated GlobalEntityTypeAttributes#put for enchantwithmob:enchanter, use EntityAttributeCreationEvent instead.

Can i ignore that?

**Comment by baguchan** [comment]
yeah. you can Ignore that
