### ISSUE TITLE
lost connection: Invalid player data

### ISSUE THREAD

**Issue by Sunekaer** [baguchan/EnchantWithMob-Forge#22]
Error when joining the game
https://pste.me/v1/paste/RdHBvidQQzI/raw

**Comment by baguchan** [comment]
![2022-04-08_11 07 18](https://user-images.githubusercontent.com/88538210/162349099-babdbfe3-9cab-4292-99ba-17c378228d11.png)
when I test my server, not go wrong(I can join server in the minecraft server with enchantwithmob)
what forge version you using?

**Comment by Sunekaer** [comment]
this was on .41, tho i disabled the mod for a few days and than then I enabled it again it just worked

**Comment by baguchan** [comment]
hmm strange
