### ISSUE TITLE
Entity Crash

### ISSUE THREAD

**Issue by LocalCrab** [baguchan/EnchantWithMob-Forge#3]
Not to entirely sure whats crashing my game but whenever I get close to a woodland mansion, I get a crash saying something about an entity. I provided the screenshots and the crash file
![image](https://github.com/baguchan/EnchantWithMob-Forge/assets/70494210/0667689c-d69f-47ae-84ab-04dc18cadc53)
![image2](https://github.com/baguchan/EnchantWithMob-Forge/assets/70494210/12bd501d-e805-4d75-87fa-d63a5e38ccad)
[lastlog.txt](https://github.com/baguchan/EnchantWithMob-Forge/files/13197178/lastlog.txt)

**Comment by baguchi** [comment]
seems like illager's wear armor's enchant with mob compat not working and causing it
also Illager wear armor's author said no longer update 1.19.2 in this page. so let me know
https://github.com/seymourimadeit/IllagersWearArmor/issues/27
