### ISSUE TITLE
Latest 1.19.2 version is broken

### ISSUE THREAD

**Issue by ModernGamingWorld** [baguchan/EnchantWithMob-Forge#30]
[crash-2022-10-10_16.56.50-client.txt](https://github.com/baguchan/EnchantWithMob-Forge/files/9749482/crash-2022-10-10_16.56.50-client.txt)

**Comment by baguchan** [comment]
https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor/files/4029859
Illager Wear Armor Update Supporting newer EnchantWithMob
