### ISSUE TITLE
1.19.2 forge creative bug

### ISSUE THREAD

**Issue by tenzedkariyu19** [baguchan/EnchantWithMob-Forge#37]
there are no mob enchanter. enchanter books,mob unenchant books in the creative inventory. the only books shown are the spawn egg and protection 4 books

**Comment by baguchan** [comment]
did you tried newer version?

**Comment by tenzedkariyu19** [comment]
im using 1.19.2-7.4.1 forge

**Comment by baguchan** [comment]
I tried newer version too but not happening
I guess it compability bug sorry
