### ISSUE TITLE
Crash rendering entity in world 

### ISSUE THREAD

**Issue by Andyghandi** [baguchan/EnchantWithMob-Forge#4]
Hi, I experienced a sudden crash in my world. I cannot enter the world again. (Though I have backup ofc). Seems to be a rendering issue with the husk mob, but I could be wrong. Anyway here's the report:

Minecraft version: 1.16.5
Forge version: forge-1.16.5-36.1.24
Optifine version: OptiFine_1.16.5_HD_U_G7

[crash-2021-06-22_20.27.42-client.txt](https://github.com/baguchan/EnchantWithMob-Forge/files/6696672/crash-2021-06-22_20.27.42-client.txt)

**Comment by baguchan** [comment]
Have you tried without optifine?
Often not drawn due to optifine
