### ISSUE TITLE
In Game Client Crash: Pose stack not empty

### ISSUE THREAD

**Issue by Blunder-G** [baguchan/EnchantWithMob-Forge#43]
My game crashed in game. After a quick research on internet i learned that it is related to the Enchant With Mob

[crash-2023-06-19_20.06.45-client.txt](https://github.com/baguchan/EnchantWithMob-Forge/files/11790644/crash-2023-06-19_20.06.45-client.txt)

[debug.log](https://github.com/baguchan/EnchantWithMob-Forge/files/11790647/debug.log)

**Comment by TenerPVPs** [comment]
Iam having too, can i see your mod list?

**Comment by BugmanBugman** [comment]
https://hastebin.com/share/uniqiwawuw.yaml
I've traced it down to alex's mobs

**Comment by baguchan** [comment]
sorry for late. I solved what should do

**Comment by TenerPVPs** [comment]
> 

I did too, gonna mixin alex mobs to fix it
