### ISSUE TITLE
[1.16.5Forge] Multishot mob enchant bug with Hunter illager boomerang

### ISSUE THREAD

**Issue by GoldenTotem** [baguchan/EnchantWithMob-Forge#49]
If you enchant yourself with multishot enchant than use boomerang in mod [Hunter illager](https://www.curseforge.com/minecraft/mc-mods/hunterillager), it will be copied. One become three.
Arrows generated by multishot will disappear when they attach to a block but boomerang don't, which cause the problem, I think.

**Comment by baguchan** [comment]
dupicate #50 don't multi post same issues
