### ISSUE TITLE
Suggestion: Allow disabling the enchanter armor in config

### ISSUE THREAD

**Issue by rafaelkai** [baguchan/EnchantWithMob-Forge#5]
As the title says, just because some players might find weird to be able to wear Illager armor (the design isn't very vanilla-friendly so to speak), and since the rest of Illagers don't drop their armor. Cheers :)

**Comment by baguchi** [comment]
hmm are you using illager wear armor mod? or just want disable enchanter wear armor on my mod?
Illager Wear Armor mod do the same behavior and has Compat about EnchantWithMob

**Comment by rafaelkai** [comment]
I want to specifically disable these items added by Enchant with Mob:

- Enchanter Hat
- Enchanter Cloth
- Enchanter Boots

**Comment by baguchi** [comment]
sorry for misunderstand.
will do!

**Comment by rafaelkai** [comment]
Thansks! :)

**Comment by rafaelkai** [comment]
BTW would there be any chance to remove the following itemss too?

- Mob UnEnchant Book
- Mob Enchant Book
- Enchanters Book

It would be nice to only have the Enchanter mob and not the new books. Cheers!

**Comment by rafaelkai** [comment]
Seems that mob enchanting book is not disabling correctly, I'm still finding it in loot (the description of the item says its disabled though). Also, it would be nice if advancements related to disabled items got disabled too, ex: "Hidden Books"
