### ISSUE TITLE
[1.16.5Forge] Multishot mob enchant bug with Hunter illager boomerang

### ISSUE THREAD

**Issue by GoldenTotem** [baguchan/EnchantWithMob-Forge#50]
If you enchant yourself with multishot enchant then use boomerang in mod [Hunter illager](https://www.curseforge.com/minecraft/mc-mods/hunterillager), it will be copied. One become three.
Arrows generated by multishot will disappear when they attach to a block but boomerang don't, this is the cause of the problem, I think.

**Comment by baguchan** [comment]
sorry 1.16.5 is no longer support
